import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@mantine/core/styles.css"
import "./globals.css"
import theme from "../../theme"
import { MantineProvider } from "@mantine/core"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "RH Shop",
  description: "Generated by @rizkyhaksono",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark" theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
