import BaseLayout from "@/components/layout/base-layout"
import { Container, SegmentedControl } from "@mantine/core"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Home | RH Shop",
  description: "Generated by @rizkyhaksono",
}

export default function Home() {
  return (
    <BaseLayout>
      <Container>
        <SegmentedControl fullWidth color="blue" data={["React", "Angular", "Vue", "Svelte"]} />
      </Container>
    </BaseLayout>
  )
}
