import BaseLayout from "@/components/layout/base-layout"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Discover | RH Shop",
  description: "Generated by @rizkyhaksono",
}

export default function DiscoverLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <BaseLayout>{children}</BaseLayout>
}
